name: lint-pr

# Run on PR changing files in plugins dir against main
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'plugins/**'

jobs:
  lint:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      # Checkout new commit and prior HEAD
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # Get diff
      - name: Get Diff
        run: echo "DIFF=`git diff --name-only HEAD~ HEAD`" >> $GITHUB_ENV

      # Lint all plugins/** files in diff (filtering of diff occurs in Python)
      - name: Lint
        run: python .github/scripts/lint.py $DIFF


# Lint all files in plugins
  # If anything outside of plugins is changed then fail?

# Grab the target repo and validate it?
  # Description?
  # README?
  # Env files?

