name: lint-pr

# Run on PR changing files in plugins dir against main
on:
  pull_request:
    # branches:
    #   - 'main'
    # paths:
    #   - '/plugins/**'
    workflow_dispatch:

jobs:
  lint-yml:
    runs-on: ubuntu-latest
    outputs:
      ENV_FILES: ${{ steps.lint.outputs.ENV_FILES }}

    steps:
      # Checkout new commit and prior HEAD
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # Get diff
      # This feels odd to me got it from
      # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#multiline-strings
      - name: Get Diff
        run: |
          {
            echo 'DIFF<<EOF'
            git diff --name-only HEAD~ HEAD
            echo EOF
          } >> "$GITHUB_ENV"

      # Lint all plugins/** files in diff (filtering of diff occurs in Python)
      - name: Lint Yml and Get Env Files
        id: lint
        run: python .github/scripts/lint.py ${{ secrets.GITHUB_TOKEN }} $DIFF

  lint-envs:
    runs-on: ubuntu-latest
    needs: lint-yml
    strategy:
      matrix:
        url: ${{ fromJSON(needs.lint-yml.outputs.ENV_FILES) }}

    steps:
      - name: 'setup miniconda'
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: ''
          architecture: 'x64'
          auto-activate-base: true
          miniconda-version: 'latest'

      - name: Test
        env:
          url: ${{ matrix.url }}
        run: |
          echo $url
          conda create -y -n test $url
          conda activate $url
          qiime info
    # strategy:
    #   matrix:
    #     env-file: ${{ needs.lint-yml.outputs.ENV_FILES }}

    # steps:
    #   - name: Echo
    #     env:
    #       file: ${{ matrix.env-file }}

    #     run: echo $color

# Lint all files in plugins
  # If anything outside of plugins is changed then fail?

# Grab the target repo and validate it?
  # Description?
  # README?
  # Env files?

