name: lint-pr

# Run on PR changing files in plugins dir against main
on:
  pull_request:
    # branches:
    #   - 'main'
    # paths:
    #   - '/plugins/**'
    workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout new commit and prior HEAD
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # Get diff
      # This feels odd to me got it from
      # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#multiline-strings
      - name: Get Diff
        run: |
          {
            echo 'DIFF<<EOF'
            git diff --name-only HEAD~ HEAD
            echo EOF
          } >> "$GITHUB_ENV"

      # Lint all plugins/** files in diff (filtering of diff occurs in Python)
      - name: Lint
        run: python .github/scripts/lint.py ${{ secrets.GITHUB_TOKEN }} $DIFF


# Lint all files in plugins
  # If anything outside of plugins is changed then fail?

# Grab the target repo and validate it?
  # Description?
  # README?
  # Env files?

