# TODO: This needs a PAT set up on the qiime2 GitHub account to facilitate this
# action pushing to q2view from library-catalog
name: push-updated-errors-to-q2view

# Run any time new errors are pushed to main
on:
  push:
    branches:
      - 'main'
    paths:
      - 'errors/**'
  workflow_dispatch:

jobs:
  push-error-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout self
        uses: actions/checkout@v4
        with:
          ref: 'add-error-tracker'
          path: './library-catalog'
          sparse-checkout: 'errors/'
          sparse-checkout-cone-mode: 'false'
          fetch-depth: 1

      - name: Checkout q2view
        uses: actions/checkout@v4
        with:
          repository: 'qiime2/q2view'
          token: ${{ secrets.BOT_PAT }}
          ref: 'issue-22'
          path: './q2view'
          sparse-checkout: 'static/errors/'
          sparse-checkout-cone-mode: 'false'
          fetch-depth: 1

      - name: Copy new errors
        run: |
          rm -r ./q2view/static/errors
          cp -r ./library-catalog/errors  ./q2view/static/

      - name: Push updated error list to view
        run: |
          git config --global user.name 'q2d2'
          git config --global user.email 'q2d2@noreply@gmail.com'
          cd ./q2view
          git commit -am "Updating errors"
          git push origin issue-22
